# Generated by Django 4.2.11 on 2024-08-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recommend",
            "0002_remove_book_pdf_url_book_read_url_alter_book_author_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="buy_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
